### ISSUE TITLE
[1.18.1] Most config options are not working. (Stacksize, Dropamount, Tag List, Mod List etc.)

### ISSUE THREAD

**Issue by Gbergz** [CodersDownUnder/Loot-Bag-Mod#24]
Minecraft Version: 1.18.1
Mod Version: 4.0.0 | https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3568417

**Describe the bug**
The config opttions: Stacksize, Dropamount, Tag List, Mod List maybe more lists. Are not working. Entries I've put in Mod List or Tag list are still dropping from the loot bags I open.

**To Reproduce**
1. Add Entries to Lists
2. Items still drop
3. Profit.

**Expected behavior**
That the lists are working correctly.

**-** Gbergz

**Comment by Trhod17** [comment]
Hopefully Fixed Now [https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3596787](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3596787)

and incase it hasnt been approved yet on curseforge [https://modrinth.com/mod/lootbagmod/version/BHQ48ybn](https://modrinth.com/mod/lootbagmod/version/BHQ48ybn)

**Comment by Gbergz** [comment]
Doesn't look like it's working. MinSize, MaxSize drops, mod blacklist, tag list etc. 
Using you're latest release linked above.

**Comment by Gbergz** [comment]
Wait hold on, should I use the config in the normal /config/ folder? Or use the one in the serverconfig folder within the world file?
A little confusing that both exists..

Edit: Anyways, tried both. Config's still not working properly.

**Comment by Trhod17** [comment]
the server config (which is the correct worked fine for me so im not sure whats going on

**Comment by Gbergz** [comment]
> the server config (which is the correct worked fine for me so im not sure whats going on

Found an issue with my file, after updating and fixing that it's now working. I'll report if I findanything else.

**Comment by Gbergz** [comment]
Okay, after more investigating it seems the Tag List, Mod List & Contain List isn't working. Maybe more.

But MinSize MaxSize is now working.

**Comment by Gbergz** [comment]
Any ideas?

**Comment by Trhod17** [comment]
Should be fully fixed now 
[https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3600733](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3600733)

**Comment by Gbergz** [comment]
That latest update broke all of the configs 😅 including minSize and maxSize.

Edit: Also while I'm here. Sometimes Loot Bags doesn't give anything. This has been reported by users in my modpack, though I have yet to have had it happen to me, so it seems random. Still annoying..

**Comment by Trhod17** [comment]
the configs have moved to the worldsaves folder, and with the issue of sometimes giving nothing i never came across that in my testing

**Comment by Gbergz** [comment]
> the configs have moved to the worldsaves folder.

Yeah, that is the one I'm using. Config doesn't work on the recent update though.

**Comment by Gbergz** [comment]
Back to the "lootbags give nothing sometimes";
The console/logs gets spammed, and the game lags for a bit.
```
[01:13:15] [Render thread/INFO]: LootBagMod Error: Null
[01:13:15] [Server thread/INFO]: LootBagMod Error: Null
[01:13:16] [Render thread/INFO]: LootBagMod Error: Null
[01:13:16] [Server thread/INFO]: LootBagMod Error: Null
[01:13:16] [Render thread/INFO]: LootBagMod Error: Null
[01:13:17] [Server thread/INFO]: LootBagMod Error: Null
[01:13:17] [Render thread/INFO]: LootBagMod Error: Null
[01:13:17] [Server thread/INFO]: LootBagMod Error: Null
[01:13:17] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2036ms or 40 ticks behind
[01:13:18] [Render thread/INFO]: LootBagMod Error: Null
[01:13:19] [Server thread/INFO]: LootBagMod Error: Null
[01:13:19] [Render thread/INFO]: LootBagMod Error: Null
[01:13:20] [Server thread/INFO]: LootBagMod Error: Null
[01:13:21] [Render thread/INFO]: LootBagMod Error: Null
[01:13:21] [Server thread/INFO]: LootBagMod Error: Null
[01:13:22] [Render thread/INFO]: LootBagMod Error: Null
[01:13:23] [Server thread/INFO]: LootBagMod Error: Null
```
That's what shown in the logs when it happens.
On singleplayer & multiplayer.

**Comment by Trhod17** [comment]
can you send me your config file

**Comment by Gbergz** [comment]
I'll send it when I'm on my PC.

Also, config should work when an ID isn't found right? A non existent ID shouldn't matter, right? Because I'm using my extremely filtered itemBlacklist entries from 1.16.5, works fine in my testings atleast. Didn't wanna be bothered redoing all the work on it I did on 1.16, would've been sad.
 
No issues for me. Except for some users that report that error I sent above. Which I have no idea how to reproduce. Pretty sure it's not caused by my list though since they've tried using a new config and it still occurred.

Hm..

(Config is re-generated for 1.18 then I just copied all my entries in the different Blacklists. Like tagList, and normal list.)

**Comment by Gbergz** [comment]
Here's the config (in **.txt** since GH doens't support **.toml**.)
[lootbagmod-server.txt](https://github.com/CodersDownUnder/Loot-Bag-Mod/files/7845431/lootbagmod-server.txt)

**Comment by Trhod17** [comment]
which version of the mod are you using because those errors where changed to be more useful in v4.2.0

The server config should look something like this you can just copy your existing lists from your old config
[lootbagmod-server.txt](https://github.com/CodersDownUnder/Loot-Bag-Mod/files/7845715/lootbagmod-server.txt)

incorrect names shouldnt matter because all matching is soft matching so if it dosent exist, it just moves on to the text item on the list

**Comment by Gbergz** [comment]
> which version of the mod are you using because those errors where changed to be more useful in v4.2.0

Using v4.1.0. because 4.2.0 doesn't work for me. minSize and maxSize, tags etc are not being read by config it seems.

> The server config should look something like this you can just copy your existing lists from your old config

I'll try that config, paste my values & try 4.2.0 again.

> incorrect names shouldnt matter because all matching is soft matching so if it dosent exist, it just moves on to the text item on the list

Sweet, thanks for clarification.

**Comment by Gbergz** [comment]
Using 4.2.0 now using the new config, with my pasted values. Doesn't look like anything's working now. TagList, ContainList, Normal List.. every list I guess. Except MinSize and MaxSize.

Edit: And with 4.2.0 there's a big delay between opening the loot bags. Latency lag almost.

**Comment by Gbergz** [comment]
Can add that using /reload ingame then using a loot bag wont give you any loot.
Loot bag breaks or something.

Console gets printed with this:
[Render thread/INFO]: LootBagMod Error: Null

**Comment by Gbergz** [comment]
Actually this `"[Render thread/INFO]: LootBagMod Error: Null"` error seems to happen without a reload sometimes for users in my modpack. Just lags and gives nothing but air. Not really sure what causes it .. very random issue.

It's been reported multiple times. And regenerating the config seems to fix it most of the times. 
(It'll grab the config from the defaultconfig folder I've set.)

Hm..
